# Generated by Django 6.0.2 on 2026-04-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('acc_number', models.BigAutoField(default=1234567891234, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('nomine', models.CharField(max_length=32)),
                ('pin', models.CharField(default='0000', max_length=64)),
                ('balance', models.FloatField(default=1000)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escn.gender')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escn.relationship')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escn.state')),
            ],
        ),
    ]
